# Generated by Django 5.1.6 on 2025-03-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_staff_email_staff_gender_staff_name_staff_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.course",
            ),
        ),
    ]
