# Generated by Django 5.1.6 on 2025-03-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_staff_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
