# Generated by Django 5.1.6 on 2025-03-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_exam_examresult_message_question_examresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(default="", max_length=50),
        ),
    ]
